#!/usr/bin/env python3
"""
Download and extract Yambda-5B's precomputed audio embeddings (Yandex Music,
huggingface.co/datasets/yandex/yambda) -- the audio-modality dataset for this
project (instructor asked for audio/text/image coverage, not just text/image).

embeddings.parquet is a standalone 13.8GB file, separate from the much larger
(195GB) user-interaction logs the rest of that repo hosts -- this script pulls
ONLY that file via huggingface_hub, not the full repo.

Embeddings were generated by a CNN inspired by Contrastive Learning of
Musical Representations (CLMR, Spijkervet et al. 2021) -- a real audio
embedding model, not a raw-audio dataset requiring us to run inference
ourselves. Schema: item_id, embed, normalized_embed -- normalized_embed is
already unit-norm, saving the force-normalize step every other dataset in
this project has needed.

Requires: pip install huggingface_hub pyarrow pandas
Requires: hf auth login (a Hugging Face account token) -- this repo is public,
no gating, but the CLI still needs to be authenticated for hf_hub_download in
some environments.
"""
import os
import numpy as np

REPO_ID = "yandex/yambda"
FILENAME = "embeddings.parquet"
OUT_CORPUS = "yambda_audio_corpus.npy"
OUT_IDS = "yambda_audio_item_ids.npy"

def main():
    from huggingface_hub import hf_hub_download
    import pandas as pd

    print(f"Downloading {FILENAME} from {REPO_ID} (13.8GB, standalone file, "
          f"NOT the full 195GB repo)...")
    local_path = hf_hub_download(repo_id=REPO_ID, filename=FILENAME, repo_type="dataset")
    print(f"  Downloaded to {local_path}")

    print("\nLoading parquet (this can take a few minutes for a 13.8GB file)...")
    df = pd.read_parquet(local_path, columns=["item_id", "normalized_embed"])
    print(f"  Loaded {len(df)} rows")

    print("\nInspecting embedding structure...")
    first = df["normalized_embed"].iloc[0]
    dim = len(first)
    print(f"  Embedding dimensionality: {dim}")
    print(f"  First embedding norm (should be ~1.0 since this is normalized_embed): "
          f"{np.linalg.norm(np.array(first, dtype=np.float32)):.6f}")

    print(f"\nStacking {len(df)} embeddings into a ({len(df)}, {dim}) float32 array "
          f"(this needs ~{len(df) * dim * 4 / 1e9:.1f}GB of RAM)...")
    corpus = np.stack(df["normalized_embed"].to_numpy()).astype(np.float32)
    item_ids = df["item_id"].to_numpy()

    print(f"  corpus shape: {corpus.shape}")
    norms = np.linalg.norm(corpus[:2000], axis=1)
    print(f"  norm check (first 2000): mean={norms.mean():.6f}, std={norms.std():.6f} "
          f"(should be ~1.0/~0.0 if truly pre-normalized)")

    print(f"\nSaving corpus to {OUT_CORPUS} and item IDs to {OUT_IDS}...")
    np.save(OUT_CORPUS, corpus)
    np.save(OUT_IDS, item_ids)
    print("Done. You can now delete the cached parquet file if disk space is tight "
          f"(huggingface_hub cache, not {local_path} itself which IS that cache path).")

if __name__ == "__main__":
    main()
